__object__:
  path: services.world_r1_strict.native.depth_anything_3.model.reconstruction_model
  name: NestedDepthAnything3Net
  args: as_params

anyview:
  __inherit__: services.world_r1_strict.native.depth_anything_3.configs.reconstruction-giant

metric:
  __inherit__: services.world_r1_strict.native.depth_anything_3.configs.reconstruction-metric-large
