"""v0.8 model port, component ownership, and component-only state I/O."""

from visual_rl.models.interface import (
    BatchProjectableModelPayload,
    BatchRowProjection,
    ModelAdapter,
    ModelInput,
    ModelLatentSpec,
    ModelPortError,
    ModelPrediction,
)
from visual_rl.models.lifecycle.components import (
    ComponentBinding,
    ComponentLifecycleError,
    ComponentLoadSession,
    ComponentManager,
    ComponentManagerError,
    ComponentResidencyError,
    ComponentRole,
    ExecutionMode,
    ModelComponents,
    OwnershipState,
    Residency,
    ResourceOwner,
    ResourcePlan,
)
from visual_rl.models.numerics.policy import (
    FloatingBufferPolicy,
    ForwardAutocastPolicy,
    FrozenParameterPolicy,
    ModelExecutionNumericsEvidence,
    ModelNumericsPolicyError,
    ParameterDTypePolicy,
    ParameterDTypePolicyOwner,
    ParameterViewEvidence,
    ParameterViewMode,
    require_parameter_view_evidence,
)
from visual_rl.models.numerics.runtime import (
    MODEL_RUNTIME_NUMERICS_SCHEMA_VERSION,
    ModelRuntimeNumerics,
)
from visual_rl.models.preprocessing import (
    ModelPreprocessConsumerSpec,
    ModelPreprocessSpec,
)
from visual_rl.models.scheduler import (
    SCHEDULER_ARTIFACT_BLUEPRINT_SCHEMA,
    ModelScheduleContext,
    SchedulerArtifactBlueprint,
)
from visual_rl.models.state.io import (
    AtomicRestoreError,
    ModelParameterState,
    ModelStateAdapter,
    StateTopologyError,
)
from visual_rl.models.state.parameters import (
    NamedTrainableParameter,
    ParameterStateError,
    ParameterStateManager,
    ParameterTopology,
    ParameterTopologyEntry,
)
from visual_rl.models.state.projection import (
    MODEL_STATE_PROJECTION_SCHEMA_VERSION,
    ModelComponentStateMembership,
    ModelParameterStateMembership,
    ModelStateProjection,
    ModelStateProjectionError,
)

__all__ = (
    "MODEL_RUNTIME_NUMERICS_SCHEMA_VERSION",
    "MODEL_STATE_PROJECTION_SCHEMA_VERSION",
    "SCHEDULER_ARTIFACT_BLUEPRINT_SCHEMA",
    "AtomicRestoreError",
    "BatchProjectableModelPayload",
    "BatchRowProjection",
    "ComponentBinding",
    "ComponentLifecycleError",
    "ComponentLoadSession",
    "ComponentManager",
    "ComponentManagerError",
    "ComponentResidencyError",
    "ComponentRole",
    "ExecutionMode",
    "FloatingBufferPolicy",
    "ForwardAutocastPolicy",
    "FrozenParameterPolicy",
    "ModelAdapter",
    "ModelComponentStateMembership",
    "ModelComponents",
    "ModelExecutionNumericsEvidence",
    "ModelInput",
    "ModelLatentSpec",
    "ModelNumericsPolicyError",
    "ModelParameterState",
    "ModelParameterStateMembership",
    "ModelPortError",
    "ModelPrediction",
    "ModelPreprocessConsumerSpec",
    "ModelPreprocessSpec",
    "ModelRuntimeNumerics",
    "ModelScheduleContext",
    "ModelStateAdapter",
    "ModelStateProjection",
    "ModelStateProjectionError",
    "NamedTrainableParameter",
    "OwnershipState",
    "ParameterDTypePolicy",
    "ParameterDTypePolicyOwner",
    "ParameterStateError",
    "ParameterStateManager",
    "ParameterTopology",
    "ParameterTopologyEntry",
    "ParameterViewEvidence",
    "ParameterViewMode",
    "Residency",
    "ResourceOwner",
    "ResourcePlan",
    "SchedulerArtifactBlueprint",
    "StateTopologyError",
    "require_parameter_view_evidence",
)
